/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalismaAlanlariIndexRouteImport } from './routes/calisma-alanlari.index'
import { Route as CalismaAlanlariSlugRouteImport } from './routes/calisma-alanlari.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalismaAlanlariIndexRoute = CalismaAlanlariIndexRouteImport.update({
  id: '/calisma-alanlari/',
  path: '/calisma-alanlari/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalismaAlanlariSlugRoute = CalismaAlanlariSlugRouteImport.update({
  id: '/calisma-alanlari/$slug',
  path: '/calisma-alanlari/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calisma-alanlari/$slug': typeof CalismaAlanlariSlugRoute
  '/calisma-alanlari/': typeof CalismaAlanlariIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calisma-alanlari/$slug': typeof CalismaAlanlariSlugRoute
  '/calisma-alanlari': typeof CalismaAlanlariIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calisma-alanlari/$slug': typeof CalismaAlanlariSlugRoute
  '/calisma-alanlari/': typeof CalismaAlanlariIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calisma-alanlari/$slug' | '/calisma-alanlari/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calisma-alanlari/$slug' | '/calisma-alanlari'
  id: '__root__' | '/' | '/calisma-alanlari/$slug' | '/calisma-alanlari/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalismaAlanlariSlugRoute: typeof CalismaAlanlariSlugRoute
  CalismaAlanlariIndexRoute: typeof CalismaAlanlariIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calisma-alanlari/': {
      id: '/calisma-alanlari/'
      path: '/calisma-alanlari'
      fullPath: '/calisma-alanlari/'
      preLoaderRoute: typeof CalismaAlanlariIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calisma-alanlari/$slug': {
      id: '/calisma-alanlari/$slug'
      path: '/calisma-alanlari/$slug'
      fullPath: '/calisma-alanlari/$slug'
      preLoaderRoute: typeof CalismaAlanlariSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalismaAlanlariSlugRoute: CalismaAlanlariSlugRoute,
  CalismaAlanlariIndexRoute: CalismaAlanlariIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
